### ISSUE TITLE
stuck in "Learning embedding..."

### ISSUE THREAD

**Issue by galyona** [lejon/T-SNE-Java#14] opened 2017-04-24 14:46 UTC
Hi,

I ran the example code (on mnist2500_x.txt) and it works great.

However, when I try to do it on my own data, iterations don't begin: It's stuck on "Learning embedding...".

My data has 4096 features, so I expect to be slower but still work. 

Is there an expected problem when the number of observations is smaller than the number of features?

**Comment by galoosh** [comment] 2017-04-26 16:29
I was able to replicate this using random data. I noticed that it only happens when I pass parallel = True

**Comment by lejon** [comment] 2017-10-15 10:24
Could you show the full command line and how you create the random data, so I can try to reproduce the problem?

**Comment by thsa** [comment] 2018-10-26 07:10
First many thanks for the nice Java implementation. We have the same problem (ParallelBHTsne hanging on "Learning embedding"). In our case the problem happens with small data files, e.g. with the attached file using x,y,z as input columns (perplexity: 10, dimensions: 50, iterations: 1000). We use the GitHub t-SNE source from 26-Apr-2018. The non-parallel BHTSne class works nicely.

[data.txt](https://github.com/lejon/T-SNE-Java/files/2518108/data.txt)

**Comment by lejon** [comment] 2018-10-26 08:05
Ok, great with an example. Many thanks! I’ll try to find time to look at it, but unfortunately it won’t happen until earliest in a couple of weeks.

BR
-Leif

**Comment by arofab** [comment] 2019-04-04 10:53
Hi

This issue seems to be caused by line #152 of ParallelBHTsne.java, in updateGradient method.
The "limit" parameter passed to RecursiveGradientUpdater constructor can be 0 for small datasets (when no. of obervations is less than 10 times the number of available cores):
   `N/(Runtime.getRuntime().availableProcessors()*10)`
I suggest using a fixed limit in these cases, writing the method as follows:

```
void updateGradient(int N, int no_dims, double[] Y, double momentum, double eta, double[] dY, double[] uY,
        double[] gains) {
    int limit = N/(Runtime.getRuntime().availableProcessors()*10);
    if (limit < 100)
        limit = 100;
    RecursiveGradientUpdater dslr = new RecursiveGradientUpdater(N, no_dims, Y, momentum, eta, dY, uY, gains,0,N * no_dims,limit);                
    gradientPool.invoke(dslr);
}
```

Greeetings,
Fabrizio

**Comment by thsa** [comment] 2019-04-10 09:45
thanks a lot. This seems to fix the issue.

Best wishes, Thomas

**Comment by lejon** [comment] 2020-09-25 19:10
Great! Many thanks for the patch! I’ll have a look!

**Comment by lejon** [comment] 2020-09-25 19:25
About time you say... :)

**Comment by lejon** [comment] 2020-09-25 19:26
Did I say a couple of weeks, I must have meant a couple of years.... Crazy how time files...

**Comment by lejon** [comment] 2020-09-25 21:24
I managed to re-create the problem with the dataset from @thsa, and have now implemented a fix.
This is fixed in commit https://github.com/lejon/T-SNE-Java/commit/a95bc0b912cac192d7e2883f83fa79db18917c72

**Comment by lejon** [comment] 2020-09-25 21:25
Thanks all for the feedback, suggestions and dataset to help re-create the problem!

**Closed by lejon** 2020-09-25 21:24 UTC
